language: php

php:
  - 5.3

before_script:
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash

script:
  - drush make springboard.build ../springboard
  - cd ../springboard
  - test -d profiles/sbsetup
  - test -d profiles/vih_dk/modules/contrib
  - test -d profiles/vih_dk/modules/vih
  - test -d profiles/vih_dk/themes
